apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 10
  template:
    metadata:
      labels:
        name: web
    spec:
        containers:
          - name: redis
            image: redis
            ports:
              - containerPort: 6379
                name: redis
                protocol: TCP
          - name: python
            image: emihamza/py-red:latest
            env:       
              - name: "REDIS_HOST"
                value: "localhost"
            ports:
              - containerPort: 5000
                name: http
                protocol: TCP   
